In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
import os

os.environ["KHISTO_BIN_DIR"] = (
    "/home/elouen/python/khisto-python/src/khiops/build/linux-gcc-debug/bin/khisto"
)
from khisto import histogram, histogram_df, cumulative_distribution_df

In [16]:
import random
import numpy as np

x = np.array([random.gauss(0, 1) for _ in range(1000)])

In [17]:
histogram(x)

(array([0.01788235, 0.12061538, 0.244     , 0.35259259, 0.192     ,
        0.0832    , 0.01047273]),
 array([-3.125  , -2.0625 , -1.25   , -0.75   ,  0.9375 ,  1.4375 ,
         2.0625 ,  3.78125]))

In [18]:
import jax

x = jax.numpy.array([random.gauss(0, 1) for _ in range(1000)])

In [19]:
histogram(x)

(Array([0.01436735, 0.12685715, 0.26584616, 0.41466665, 0.272     ,
        0.08123077, 0.00956322], dtype=float32),
 Array([-2.828125, -2.0625  , -1.1875  , -0.375   ,  0.375   ,  1.375   ,
         2.1875  ,  3.546875], dtype=float32))

In [20]:
histogram(x.tolist())

([0.01436734694,
  0.1268571429,
  0.2658461538,
  0.4146666667,
  0.272,
  0.08123076923,
  0.009563218391],
 [-2.828125, -2.0625, -1.1875, -0.375, 0.375, 1.375, 2.1875, 3.546875])

In [21]:
import pandas as pd

x = pd.Series([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x7bd3c8bc4dc0>
 [
   0.003,
   0.032,
   0.114,
   0.2493333333,
   0.3768888889,
   0.2613333333,
   0.1051428571,
   0.02220408163
 ],
 [
   -3.625,
   -2.625,
   -1.875,
   -1.375,
   -0.625,
   0.5,
   1.25,
   2.125,
   2.890625
 ])

In [22]:
import polars as pl

x = pl.Series("x", [random.gauss(0, 1) for _ in range(1000)])
histogram(x)

(<pyarrow.lib.DoubleArray object at 0x7bd3c8bc4820>
 [
   0.01333333333,
   0.052,
   0.196,
   0.329,
   0.444,
   0.282,
   0.164,
   0.1,
   0.02438095238
 ],
 [
   -3.25,
   -2.5,
   -1.5,
   -1,
   0,
   0.5,
   1,
   1.5,
   2,
   2.65625
 ])

In [23]:
histogram_df(x).to_native()

lower_bound,upper_bound,length,frequency,probability,density,granularity,is_best,center
f64,f64,f64,i64,f64,f64,i32,bool,f64
-3.25,-2.0,1.25,32,0.032,0.0256,3,true,-2.625
-2.0,-1.0,1.0,128,0.128,0.128,3,true,-1.5
-1.0,1.0,2.0,692,0.692,0.346,3,true,0.0
1.0,2.0,1.0,132,0.132,0.132,3,true,1.5
2.0,2.65625,0.65625,16,0.016,0.024381,3,true,2.328125
…,…,…,…,…,…,…,…,…
-3.25,0.0,3.25,489,0.489,0.150462,1,false,-1.625
0.0,2.65625,2.65625,511,0.511,0.192376,1,false,1.328125
-3.25,-2.0,1.25,32,0.032,0.0256,2,false,-2.625


In [24]:
cum_df = cumulative_distribution_df(x).to_native()
cum_df

position,granularity,is_best,cumulative_probability
f64,i32,bool,f64
-3.25,0,false,0.0
2.65625,0,false,1.0
-3.25,1,false,0.0
0.0,1,false,0.489
2.65625,1,false,1.0
…,…,…,…
0.5,4,false,0.711
1.0,4,false,0.852
1.5,4,false,0.934


In [25]:
cum_df.filter(pl.col("granularity") == 0)

position,granularity,is_best,cumulative_probability
f64,i32,bool,f64
-3.25,0,false,0.0
2.65625,0,false,1.0


In [26]:
cumulative_distribution_df([1.0, 2.0, 3.0, 4.0, 5.0], granularity="best").to_native()

DuplicateError: Expected unique column names, got:
- 'is_best' 2 times